title: Stel de pinnen in voor een enkele zoemer
hero_image: images/banner.png
description: Hoe kan je de pinnen voor een enkele zoemer op je Raspberry Pi Pico instellen
version: 4
listed: false
copyedit: false
last_tested: "2022-02-15"
steps:
  - 
    title: Stel de pinnen in voor een enkele zoemer
