title: Set the pins for a single buzzer
hero_image: images/banner.png
description: How to set the pins for a single buzzer on a Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-15"
steps:
  - title: Set the pins for a single buzzer
